version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - APP_DB_NAME=thermometer_db
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./test-db-init:/docker-entrypoint-initdb.d/
  db-test:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - APP_DB_NAME=thermometer_db
    ports:
      - '5434:5432'
    volumes:
      - db-test:/var/lib/postgresql/data
      - ./test-db-init:/docker-entrypoint-initdb.d/

volumes:
  db:
    driver: local
  db-test:
    driver: local